name: Deploy Python Azure Function App to Development

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'  # Match your function app's Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Azure using service principal
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

      - name: Create ZIP of application
        run: |
          zip -r function_app.zip ./*

      - name: Deploy Azure Function App
        run: |
          az functionapp deployment source config-zip \
            --resource-group dev-tradelyncs-rg-ap \
            --name dev-tradelyncs-chat-fn-app \
            --src-path ${{ github.workspace }}/function_app.zip

      - name: Clean up ZIP
        run: |
          rm function_app.zip